#ifndef NETWORK_OBJECT_ID_H
#define NETWORK_OBJECT_ID_H

#include "acp/main.h"

#define NOID_ACP_REQUEST_IND_ID			ACP_REQUEST_IND_ID
#define NOID_ACP_REQUEST_IND_PARAM1		ACP_REQUEST_IND_PARAM1
#define NOID_ACP_REQUEST_IND_PARAM2		ACP_REQUEST_IND_PARAM2
#define NOID_ACP_REQUEST_IND_PARAM3		ACP_REQUEST_IND_PARAM3

#define NOID_ID_UNKNOWN 0
#define NOID_ID_BROADCAST 255

typedef enum {
	NOID_KIND_UNKNOWN=0,
	NOID_KIND_FIRST,
	NOID_KIND_REGULAR,
	NOID_KIND_EXTERN
} NoidKind;

#endif 
